Namespace for RDF
interledger/paymentpointers.org pull request #9
Opened 2021-04-28 14:45 UTC by michielbdejong

This adds a namespace URL for use in RDF documents.
The current text is a first version to make sure the URL http://paymentpointers.org/ns#PaymentPointer dereferences to something other than a 404; we can improve and extend it later.
See also https://github.com/solid/webmonetization/issues/9 for more details.

CC @joepie @travis @ianconsolata @rubensworks

2021-04-29 06:41 UTC, rubensworks approved these changes

2021-05-03 07:35 UTC, rubensworks requested changes

2021-05-03 07:35 UTC, rubensworks commented on 7-ns.md
> +Use `http://paymentpointers.org/ns#PaymentPointer` as the predicate when linking a WebID to a Payment Pointer. Make sure this triple lives in the profile document to which the WebID dereferences. Exa
I didn't look at this closely enough in my first review.

Following the URL conventions for ontologies, I thought `http://paymentpointers.org/ns#PaymentPointer` was a class (due to CamelCase).
However, it looks like this is here used as a predicate, for which `http://paymentpointers.org/ns#paymentPointer` (mixedCase) would be more appropriate.

I would however suggest a more generic solution, so we can leave the door open for other types of payment pointers in the future.
For example:

```turtle
<#me> a <foaf:Person> ;
  pp:hasPaymentPointer [
    a pp:InterledgerPaymentPointer;
    pp:paymentPointerValue "$alice.wallet.example".
  ].
```

Such a reified form would also allow people to include multiple pointers, and annotate them for different purposes. For example, one wallet could be used for work-related matters, while another could be used for personal things.

2021-05-03 14:10 UTC, adrianhopebailie commented
I actually think these should be in an Interledger namespace.
`paymentpointers.org` content is likely to be folded into interledger.org in the near future

cc @kincaidoneil

2021-07-20 12:08 UTC, michielbdejong commented
Thanks for the feedback, all!

OK, so let's deprecate  this `pp:PaymentPointer` proposal *as well as* `pp:hasPaymentPointer`, and open a PR on interledger.org instead.

And then we'll make it `ilp:hasPaymentPointer` following @rubensworks's improvement suggestion - thanks!

Once we have an ontology live on interledger.org, the (two or three?) projects already using `pp:PaymentPointer` and the (one?) project already using `pp:hasPaymentPointer` will all have to update to that new one.

2021-07-20 12:08 UTC, closed without merging